# Generated by Django 5.2 on 2025-04-21 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('zpid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('provider_listing_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status_type', models.CharField(blank=True, max_length=50)),
                ('status_text', models.CharField(blank=True, max_length=100)),
                ('market_status', models.CharField(blank=True, max_length=50)),
                ('price', models.CharField(blank=True, max_length=50)),
                ('unformatted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='$', max_length=10)),
                ('address', models.TextField(blank=True)),
                ('street_address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=20)),
                ('zipcode', models.CharField(blank=True, max_length=20)),
                ('is_undisclosed_address', models.BooleanField(default=False)),
                ('unit', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('beds', models.IntegerField(blank=True, null=True)),
                ('baths', models.FloatField(blank=True, null=True)),
                ('home_type', models.CharField(blank=True, max_length=50, null=True)),
                ('main_image_url', models.URLField(blank=True, null=True)),
                ('has_image', models.BooleanField(default=False)),
                ('has_video', models.BooleanField(default=False)),
                ('has_3d_model', models.BooleanField(default=False)),
                ('detail_url', models.URLField(blank=True, null=True)),
                ('has_fireplace', models.BooleanField(default=False)),
                ('has_air_conditioning', models.BooleanField(default=False)),
                ('has_spa', models.BooleanField(default=False)),
                ('has_pool', models.BooleanField(default=False)),
                ('days_on_market', models.IntegerField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_showcase', models.BooleanField(default=False)),
                ('raw_json_data', models.JSONField(blank=True, null=True)),
                ('carousel_photos', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landlord_chats', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='negotiation.property')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renter_chats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('landlord', 'Landlord'), ('renter', 'Renter'), ('bot', 'AI Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='negotiation.propertychat')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
